### ISSUE TITLE
[Bug] MySqlCdcE2eTestBase.testSyncDatabase failed 

### ISSUE THREAD

**Issue by zzzzzzzs** [apache/paimon#1056]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.4

### Compute Engine

flink

### Minimal reproduce step

tests

### What doesn't meet your expectations?

An error occurred while running testSyncDatabase, which appears to have occurred while modifying the MySQL field type

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Can you describe the details of the error and how it was reproduced?

**Comment by zzzzzzzs** [comment]
> Can you describe the details of the error and how it was reproduced?

There are currently two issues:
The first issue is that the captured change data is saved in the currentResults variable by judging the logs, but `executeUpdate ` may be in the same thread, resulting in both sets of data from `executeUpdate` being saved in the currentResults variable.
The second issue is that the operation `ALTER TABLE t1 MODIFY COLUMN v BIGINT` modifies MySQL but does not change the field type of Paimon to BIGINT. It remains as int, causing a data overflow for BIGINT.

![image](https://user-images.githubusercontent.com/25766626/236194859-0b8296cc-071b-4ecf-811e-fd3711e77276.png)

**Comment by JingsongLi** [comment]
> > Can you describe the details of the error and how it was reproduced?
> 
> There are currently two issues: The first issue is that the captured change data is saved in the currentResults variable by judging the logs, but `executeUpdate ` may be in the same thread, resulting in both sets of data from `executeUpdate` being saved in the currentResults variable. The second issue is that the operation `ALTER TABLE t1 MODIFY COLUMN v BIGINT` modifies MySQL but does not change the field type of Paimon to BIGINT. It remains as int, causing a data overflow for BIGINT.
> 
> ![image](https://user-images.githubusercontent.com/25766626/236194859-0b8296cc-071b-4ecf-811e-fd3711e77276.png)

Thanks!

**Comment by zzzzzzzs** [comment]
> 



> > > Can you describe the details of the error and how it was reproduced?
> > 
> > 
> > There are currently two issues: The first issue is that the captured change data is saved in the currentResults variable by judging the logs, but `executeUpdate ` may be in the same thread, resulting in both sets of data from `executeUpdate` being saved in the currentResults variable. The second issue is that the operation `ALTER TABLE t1 MODIFY COLUMN v BIGINT` modifies MySQL but does not change the field type of Paimon to BIGINT. It remains as int, causing a data overflow for BIGINT.
> > ![image](https://user-images.githubusercontent.com/25766626/236194859-0b8296cc-071b-4ecf-811e-fd3711e77276.png)
> 
> Thanks!

For the first issue, the order of checkResult can be adjusted to solve it. As for the second issue, it seems that updating field types and partition keys is not supported in the code.
