### ISSUE TITLE
[Bug] Snapshot expire may have unexpected behavior when snapshot.num-retained.min = 0

### ISSUE THREAD

**Issue by qidian99** [apache/paimon#1167]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.5-SNAPSHOT

### Compute Engine

Flink

### Minimal reproduce step

Setting snapshot.num-retained.min=0 in table property will cause all snapshots being expired after the maximum retain time of completed snapshots.

### What doesn't meet your expectations?

snapshot.num-retained.min should be greater than or equal to 1, so that we always has at least 1 snapshot.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
The related PR has been merged into the master repository, and I will close this issue.
