### ISSUE TITLE
[Bug] Batch query with limit failed every 3 times

### ISSUE THREAD

**Issue by schnappi17** [apache/paimon#1172]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

paimon-flink-1.16-0.4-20230503.001923-49.jar

### Compute Engine

flink 1.16.1

### Minimal reproduce step

execute 'select word, cnt from word_table limit 1', and repeat it. 
It'll succeed one time and fails 2 times, always like this.
![image](https://github.com/apache/incubator-paimon/assets/26704332/6803c761-2506-4b2c-9929-d44c6d7d8c2b)

![image](https://github.com/apache/incubator-paimon/assets/26704332/21051220-cb0f-4d67-ad0b-de7f26c723f8)
Detailed Exception:
![image](https://github.com/apache/incubator-paimon/assets/26704332/eb16b607-aeeb-4d12-907b-9556834fa26f)

### What doesn't meet your expectations?

It's wired.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Can you show the detail exceptions?

**Comment by schnappi17** [comment]
> Can you show the detail exceptions?

@JingsongLi Updated the detaild exceptions in description

**Comment by JingsongLi** [comment]
> > Can you show the detail exceptions?
> 
> @JingsongLi Updated the detaild exceptions in description, seems like a flink bug？

yes, it should be.
