### ISSUE TITLE
[Bug] ConfigOptionsDocsCompletenessITCase::testCompleteness failed when CoreOption changed

### ISSUE THREAD

**Issue by qidian99** [apache/paimon#1188]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.5-SNAPSHOT

### Compute Engine

Flink

### Minimal reproduce step

1. Change core option and run `mvn package -Pgenerate-docs -pl paimon-docs -nsu -DskipTests` as described in `paimon-docs/README.md` 

2. Run the test ConfigOptionsDocsCompletenessITCase::testCompleteness 

### What doesn't meet your expectations?

Test failed.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Can you describe the detailed reproduce step? I cannot fully understand this.

**Comment by qidian99** [comment]
After I changed some CoreOptions, and tried to rebuild the docs, it is not updating the generated docs.

However, when I run ConfigOptionsDocGenerator directly by passing 2 args (doc path and project root), the generated doc contains my change.

Therefore, I further debugged the paimon-docs module and found out the ${rootDir} variable is not well respected (at least for my maven version 3.6.3). After adding the rootDir property to `../`, the docs are correctly genearted.

@JingsongLi

**Comment by JingsongLi** [comment]
1. Modify CoreOptions.
2. mvn clean install -DskipTests
3. mvn package -Pgenerate-docs -pl paimon-docs -nsu -DskipTests

All works fine now.
What is the problem?
