### ISSUE TITLE
[Bug]  could not set execution.runtime-mode

### ISSUE THREAD

**Issue by CatchTheDog** [apache/paimon#1208]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

 paimon-flink-1.17-0.5-20230523.001944-17.jar

### Compute Engine

flink-1.17.0-bin-scala_2.12.tgz

### Minimal reproduce step

I execute " set 'execution.runtime-mode' = 'stream'; " with mistake. I can't execute " set 'execution.runtime-mode' = 'streaming'" or " set 'execution.runtime-mode' = 'batch'",with this error:

### What doesn't meet your expectations?

can't set execution.runtime-mode with streaming

### Anything else?

<img width="707" alt="image" src="https://github.com/apache/incubator-paimon/assets/38939831/8d33ff54-aeda-46ca-821f-aea732166670">

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
https://issues.apache.org/jira/browse/FLINK-32043
There is a bug in flink-sql-cli.
