### ISSUE TITLE
[Bug] Sometimes the classloader works unexpected

### ISSUE THREAD

**Issue by schnappi17** [apache/paimon#1295]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

45abddd9b8c434fdcf710bfafef34b0e4b6737d7

### Compute Engine

Flink 1.17

### Minimal reproduce step

1. mvn clean install -DskipTests
2. create catalog;
3. use catalog;
4. create table;
5. insert into

### What doesn't meet your expectations?

Sometimes it works good.

Sometimes (not always) it result in the exceptions like below:
<img width="813" alt="image" src="https://github.com/apache/incubator-paimon/assets/26704332/24013110-51c8-45ab-9b45-d2ef4730320a">

Sometimes it result in the exceptions like below:
![Untitled](https://github.com/apache/incubator-paimon/assets/26704332/106d6627-c23f-4a5a-bc71-018012c153d7)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by klion26** [comment]
@schnappi17  could you please give some reproducible steps?  cloud you please also check is there some class conflict when exception throw (by enable jvm opts -- such as `-XX:+TraceClassLoading`, or adding some log)
