### ISSUE TITLE
[Bug] Error in querying primary key table with row type column under trino

### ISSUE THREAD

**Issue by macdoor** [apache/paimon#1491]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

paimon-trino-393-0.5-20230704.000507-57.jar

### Compute Engine

Trino 420

openjdk version "17.0.7" 2023-04-18 LTS
OpenJDK Runtime Environment (Red_Hat-17.0.7.0.7-2) (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.7.0.7-2) (build 17.0.7+7-LTS, mixed mode, sharing)

### Minimal reproduce step

create 3 tables

```
drop table if exists svc1_paimon_prod.dxx.with_row;
CREATE TABLE svc1_paimon_prod.dxx.with_row (
  id                    string,
  order_attrs           row<
    ordernum            string,
    paymentmode         string
  >,
  skuNum                string,
  PRIMARY KEY (id,skuNum) NOT ENFORCED
) 
  PARTITIONED BY (skuNum);
  
  
drop table if exists svc1_paimon_prod.dxx.without_row;
CREATE TABLE svc1_paimon_prod.dxx.without_row (
  id                    string,
  skuNum                string,
  PRIMARY KEY (id,skuNum) NOT ENFORCED
) 
  PARTITIONED BY (skuNum);

drop table if exists svc1_paimon_prod.dxx.with_row_append;
CREATE TABLE svc1_paimon_prod.dxx.with_row_append (
  id                    string,
  order_attrs           row<
    ordernum            string,
    paymentmode         string
  >,
  skuNum                string
) 
  PARTITIONED BY (skuNum);
```

### What doesn't meet your expectations?

execute

`SELECT t.* FROM with_row t
`
throw exception 

```
[2023-07-04 12:25:42] [65536] Query failed (#20230704_042542_00381_hzk4t): org.apache.paimon.codegen.GeneratedClass
[2023-07-04 12:25:42] java.lang.ClassNotFoundException: org.apache.paimon.codegen.GeneratedClass

```

There is no error in querying table without_row, with_row_append

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by macdoor** [comment]
Trino 420

**Comment by JingsongLi** [comment]
It seems that you haven't copied the Paimon jar to the work node?

**Comment by macdoor** [comment]
I put paimon-trino-393-0.5-20230704.000507-57.jar in trino/plugin/paimon directory, and I can other  2 paimon table without_row and with_row_append.

**Comment by JingsongLi** [comment]
> I have put paimon-trino-393-0.5-20230704.000507-57.jar in trino/plugins/paimon directory, and I can query other 2 paimon table without_row and with_row_append.

Do you have whole stack error message?

**Comment by macdoor** [comment]
[server.log.zip](https://github.com/apache/incubator-paimon/files/11967218/server.log.zip)
Here is Trino log

**Comment by macdoor** [comment]
@JingsongLi 

[server.log-20230817.134144.zip](https://github.com/apache/incubator-paimon/files/12365899/server.log-20230817.134144.zip)

```
CREATE TABLE bb (
	bizVersion   string,
	fileBody     array<row<
		request_msg string
	>>,
	fileHead     row<
		fileSeq      string,
		recCompanyID string,
		sndCompanyID string
	>,
	fileTail     row<
		createTime   string,
		poOrderCnt   string
	>,
	raw_rowtime  timestamp(3),
	dt           string
)
PARTITIONED BY (dt) with (
'compaction.max.file-num'='100',
'full-compaction.delta-commits' = '50',
'continuous.discovery-interval' = '1s')
```

Query paimon table in Trino 423 and got error 

```
[2023-08-17 13:43:21] 0 rows retrieved in 620 ms (execution: 299 ms, fetching: 321 ms)
[2023-08-17 13:43:21] [65536] Query failed (#20230817_054320_00021_7spqn): 'io.trino.spi.block.BlockBuilder io.trino.spi.block.BlockBuilder.beginBlockEntry()'
[2023-08-17 13:43:21] java.lang.NoSuchMethodError: 'io.trino.spi.block.BlockBuilder io.trino.spi.block.BlockBuilder.beginBlockEntry()'
```

paimon-trino-422-0.5-20230817.000424-24.jar
trino-server-423

Query same table in Trino 420 and success

paimon-trino-393-0.5-SNAPSHOT-07102100.jar
trino-server-420

**Comment by JingsongLi** [comment]
This is a version support issue. Please try latest paimon-trino.
