### ISSUE TITLE
[Bug] java.lang.ClassNotFoundException: org.apache.flink.table.planner.delegation.ParserFactory

### ISSUE THREAD

**Issue by zhengtingxue** [apache/paimon#1493]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

paimon-flink-1.17-0.5-20230703.002437-67.jar

### Compute Engine

flink 1.17.1

### Minimal reproduce step

my lib jars: 
![image](https://github.com/apache/incubator-paimon/assets/19706871/3b927026-8f0d-4833-8300-dd4b406cb392)
start the sql-client.sh
./bin/sql-client.sh embedded
create catalog:

CREATE CATALOG my_catalog WITH (
    'type' = 'paimon',
    'warehouse' = 'hdfs:///path/to/warehouse'
);

### What doesn't meet your expectations?

Flink SQL> CREATE CATALOG my_catalog WITH (
>     'type' = 'paimon',
>     'warehouse' = 'hdfs:///path/to/warehouse'
> );
[ERROR] Could not execute SQL statement. Reason:
java.lang.ClassNotFoundException: org.apache.flink.table.planner.delegation.ParserFactory

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhengtingxue** [comment]
i search the flink github and paimon github,they does not contain the class ParserFactory

**Comment by JingsongLi** [comment]
Can you show the full exception stack?

**Comment by liming30** [comment]
@zhengtingxue I see that the Flink version corresponding to your `flink-sql-connector-hive` is `1.13`, and the `ParserFactory` has been renamed in a higher Flink version. You can upgrade the version of `flink-sql-connector-hive` to 1.17 and try again. cc @JingsongLi
