### ISSUE TITLE
[Bug] UnawareBucketAppendOnlyTableITCase.testCompactionInStreamingMode is not stable

### ISSUE THREAD

**Issue by FangYongs** [apache/paimon#1634]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

https://github.com/apache/incubator-paimon/actions/runs/5596335088/job/15158436649?pr=1603

### Compute Engine

flink

### Minimal reproduce step

Run ci

### What doesn't meet your expectations?

CI fails

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by EMsnap** [comment]
I'm willing to take a look at this, can you assign the issue to me please?

**Comment by EMsnap** [comment]
I'm trying to reproduce this error but fails
Looks like we need to reduce the compaction.min.file-num or increase the waiting time of compaction. However it seems like a trivial work
Could u please provide any other better ideas? @FangYongs
