### ISSUE TITLE
[Bug] Could not find artifact xxx:tests in central/apache.snapshots during "mvn clear install -DskipTests" 

### ISSUE THREAD

**Issue by YIHONG-JIN** [apache/paimon#1718]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

Master Branch
Commit id: 41997b2170dcfa32aa867bbc4573989911f05f61

### Compute Engine

No Compute Engine involved

### Minimal reproduce step

CPU: M1 Pro
OS: macOs Ventura
IDE: IntelliJ IDEA
JDK Version: Amazon Corretto Version 1.8.0 (aarm64)
Maven Version: Maven 3.8.1 Bundled (default setting provided by IntelliJ IDEA)

`git clone git@github.com:apache/incubator-paimon.git`

Open the repositories with IntelliJ IDEA, run Maven command "mvn clean install -DskipTests" with the following configurations:

![Screenshot 2023-08-02 at 7 20 05 PM](https://github.com/apache/incubator-paimon/assets/55143222/f41e368c-3e07-44be-a89c-9cf0a252ca2b)

### What doesn't meet your expectations?

Got lots of errors related to dependency issues, for example:

Could not find artifact com.google.code.findbugs:jsr305:jar:tests:1.3.9 in central (https://repo.maven.apache.org/maven2)
Could not find artifact org.apache.paimon:paimon-parent:jar:tests:0.5-SNAPSHOT in apache.snapshots (https://repository.apache.org/snapshots)

Screenshot:
![Screenshot 2023-08-02 at 7 21 35 PM](https://github.com/apache/incubator-paimon/assets/55143222/12d8275f-ec9a-4aba-8ccb-884351770961)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by zhuangchong** [comment]
@YIHONG-JIN 
Check your network? Among them, the Apache repository is on a foreign server, and it is usually very slow to download the jar, please try a few more times.

**Comment by YIHONG-JIN** [comment]
> 
I am physically in the United States so I believe that should not be the cause. But thanks for your suggestions.

**Comment by YIHONG-JIN** [comment]
> @YIHONG-JIN Check your network? Among them, the Apache repository is on a foreign server, and it is usually very slow to download the jar, please try a few more times.
I am physically in the United States so I believe that should not be the cause. But thanks for your suggestions.

**Comment by YIHONG-JIN** [comment]
> @YIHONG-JIN Check your network? Among them, the Apache repository is on a foreign server, and it is usually very slow to download the jar, please try a few more times.

I am physically in the United States so I believe that should not be the cause. But thanks for your suggestions.

**Comment by zhuangchong** [comment]
> > @YIHONG-JIN Check your network? Among them, the Apache repository is on a foreign server, and it is usually very slow to download the jar, please try a few more times.
> 
> I am physically in the United States so I believe that should not be the cause. But thanks for your suggestions. Is there a suggested maven configuration for this project?

No special configuration of maven is required. I can develop locally normally.

**Comment by YIHONG-JIN** [comment]
> > > @YIHONG-JIN Check your network? Among them, the Apache repository is on a foreign server, and it is usually very slow to download the jar, please try a few more times.
> > 
> > 
> > I am physically in the United States so I believe that should not be the cause. But thanks for your suggestions. Is there a suggested maven configuration for this project?
> 
> No special configuration of maven is required. I can develop locally normally.

I retried for several times. It looks like it is not because maven could not find the dependencies theirselves. Due to the log, maven is trying to find the "tests" of these dependencies during compilation, which is the reason why the log looks like "Could not find artifact com.google.code.findbugs:jsr305:jar:**_tests_**:1.3.9 in central (https://repo.maven.apache.org/maven2)". However, there is not such jar in central repo. 

In addition, I have also seen warnings like:
"[WARNING] Could not get tests for com.google.code.findbugs:jsr305:jar:1.3.9:compile
[WARNING] Could not get tests for org.apache.paimon:paimon-parent:pom:0.5-SNAPSHOT"

I would be thankful if someone could help me root the cause.

**Comment by YIHONG-JIN** [comment]
Update: When I try to build this project through terminal, it success. However, there are still warnings like "[WARNING] Could not get tests for org.glassfish.jersey.core:jersey-client:jar:2.30:compile", which means the cmd version Maven is also trying to find tests for dependencies, which does not exist. There is no error reported in terminal despite it is reported as an error inside IntelliJ. 

![Screenshot 2023-08-04 at 12 23 33 AM](https://github.com/apache/incubator-paimon/assets/55143222/bb44c09e-83ca-4931-b265-91984f22ba67)

Though I am not an expert of Maven, I believe it should be possible to prevent Maven from finding tests for dependencies by modifying pom.xml structures.
