### ISSUE TITLE
[Feature] Flink catalog as persistent storage for Flink metadata

### ISSUE THREAD

**Issue by hdygxsj** [apache/paimon#1804]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Why isn't the flink catalog provided by paimon available as persistent storage for pure Flink metadata, like hive's catalog？
<img width="1062" alt="截屏2023-08-13 02 18 33" src="https://github.com/apache/incubator-paimon/assets/35210666/e6faaf3d-0bab-4d42-bdd8-ebb50e043ec7">
<img width="895" alt="截屏2023-08-13 02 19 52" src="https://github.com/apache/incubator-paimon/assets/35210666/48c808c5-eb49-4df4-b4d7-1417de44f3f9">

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
> @hdygxsj Do you means to save catalog information to a storage? We would like to do this in #1481

No, I think this issue means something like `SparkGenericCatalog`. We need a `FlinkGenericCatalog` too. I am +1 for this.

**Comment by hdygxsj** [comment]
> > @hdygxsj Do you means to save catalog information to a storage? We would like to do this in #1481
> 
> No, I think this issue means something like `SparkGenericCatalog`. We need a `FlinkGenericCatalog` too. I am +1 for this.

Can you give me a chance to finish it？I'm willing to submit a PR!

**Comment by FangYongs** [comment]
Got it, I'll take it 👍

**Comment by FangYongs** [comment]
> > > @hdygxsj Do you means to save catalog information to a storage? We would like to do this in #1481
> > 
> > 
> > No, I think this issue means something like `SparkGenericCatalog`. We need a `FlinkGenericCatalog` too. I am +1 for this.
> 
> Can you give me a chance to finish it？I'm willing to submit a PR!

Assigned to you 👍

**Comment by pegasas** [comment]
great idea & work!
This will push Flink further into cloud-native steps!
Also a good way of spreading palmon!

Following this issue.

**Comment by hdygxsj** [comment]
> great idea & work! This will push Flink further into cloud-native steps! Also a good way of spreading palmon!
> 
> Following this issue.
> 
> With my understanding, it seems JDBCCatalog only supports [read-only action](https://nightlies.apache.org/flink/flink-docs-master/docs/connectors/table/jdbc/#jdbc-catalog-for-mysql) on catalog. Will Palmon Catalog be read-only or fully support like hive support?

I want to make it the same as the hive catalog, and I will try to submit PR in September to complete it

**Comment by JingsongLi** [comment]
Another work is https://github.com/apache/incubator-paimon/pull/1857 .

https://github.com/apache/incubator-paimon/pull/1857 is different with this ticket. Its goal is to be compatible with Flink's original HiveCatalog, so it requires the mandatory use of Hive Metastore.

The purpose of this ticket is to enable Paimon's FileSystem to save the connection information of all Flink connectors.
Maybe we can call this `ExternalCatalog`.
