### ISSUE TITLE
[Bug] HiveCatalog uses LocalFileIO when hadoop configuration is loaded

### ISSUE THREAD

**Issue by Paddy0523** [apache/paimon#2022]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.6-SNAPSHOT

### Compute Engine

flink1.16

### Minimal reproduce step

CREATE CATALOG my_catalog WITH (
    'type'='paimon-generic',
    'hive-conf-dir' = '/opt/Hive/hive_pkg/conf/',
    'hadoop-conf-dir' = '/opt/Hadoop/hadoop_pkg/etc/hadoop/'
);

CREATE DATABASE my_catalog.paimon_test;

CREATE TABLE my_catalog.paimon_test.word_count (
    word STRING PRIMARY KEY NOT ENFORCED,
    cnt BIGINT
) WITH (
    'connector' = 'paimon'
);

### What doesn't meet your expectations?

I expected the paimon table file to be created on hdfs, but it was actually created to the local path
<img width="1252" alt="image" src="https://github.com/apache/incubator-paimon/assets/46181516/cde9ce00-7e90-45c2-8340-0169e28e8dfe">

### Anything else?

It seems that because of my configuration, it does not start with "hdfs: //"
<img width="754" alt="image" src="https://github.com/apache/incubator-paimon/assets/46181516/3a8a8e14-bead-4b57-acb8-b971087e82f1">

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
https://github.com/apache/paimon/pull/2432 fixed this.
