### ISSUE TITLE
[Feature] Optimize the memory usage of PartitionExpire.

### ISSUE THREAD

**Issue by liming30** [apache/paimon#2023]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

1. When the partition expires, all `ManifestEntry` of the corresponding partition will be read into the memory, and then a new `ManifestEntry` whose `FileKind` is `Delete` will be generated. When the file of the expired partition is very large (hundreds of thousands), this will occupy a lot of memory.

2. In addition, when there may be conflicts in the commit, the files of the changed partitions will also be read into the memory for conflict checking.

### Solution

We may not need to read it completely into memory, but return it in a stream.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by xiangyuf** [comment]
@liming30 hi, could u pls assign this issue to me?

**Comment by JingsongLi** [comment]
Already optimized in the 0.8.0
