### ISSUE TITLE
[Feature] Implement merge/replace branch in BranchManager

### ISSUE THREAD

**Issue by FangYongs** [apache/paimon#2153]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

subtask of #1795

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by sunxiaojian** [comment]
@FangYongs If it hasn't been implemented yet, you can assign this issue to me and I'll try to solve it
