### ISSUE TITLE
[Bug] After dynamic Overwrite in Flink Batch and Spark Batch, Flink Streaming can only query the deleted data in partitions, but cannot query the inserted data in partitions

### ISSUE THREAD

**Issue by 18216499322** [apache/paimon#2163]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.5

### Compute Engine

Flink and Spark

### Minimal reproduce step

Step1
Flink1.17.1 SQL Client
CREATE CATALOG paimon WITH (
    'type' = 'paimon',
    'metastore' = 'hive',
    'uri' = 'thrift://192.168.253.132:9083',
    'warehouse' = 'hdfs://nns/warehouse/tablespace/managed/paimon'
);
SET 'execution.runtime-mode' = 'streaming';
SET 'sql-client.execution.result-mode' = 'tableau';
CREATE TABLE paimon.test.mytable_v7 (
    user_id BIGINT,
    item_id BIGINT,
    behavior STRING,
    stat_date STRING,
    PRIMARY KEY (stat_date, user_id) NOT ENFORCED
) PARTITIONED BY (stat_date)
with(
    'metastore.partitioned-table'='true',
	'changelog-producer'='lookup',
	'streaming-read-overwrite'='true'
);
insert into paimon.test.mytable_v7 values(1,1,'pv','20231016');
select * from paimon.test.mytable_v7;
![image](https://github.com/apache/incubator-paimon/assets/75019445/14a92b32-d690-41a1-a5c1-6f8932b8d6ac)

Step2
Flink1.17.1 SQL Client
SET 'execution.runtime-mode' = 'batch';
SET 'sql-client.execution.result-mode' = 'tableau';
CREATE TABLE paimon.test.mytable_v8 (
    user_id BIGINT,
    item_id BIGINT,
    behavior STRING,
    stat_date STRING,
    PRIMARY KEY (stat_date, user_id) NOT ENFORCED
) PARTITIONED BY (stat_date)
with(
    'metastore.partitioned-table'='true',
	'changelog-producer'='lookup',
	'streaming-read-overwrite'='true'
);
insert into paimon.test.mytable_v8 values(1,2,'pv','20231016');
select * from paimon.test.mytable_v8;
![image](https://github.com/apache/incubator-paimon/assets/75019445/7eb4697b-caa3-4467-8e95-f0945d391d4e)

Step3
Flink1.17.1 SQL Client
INSERT OVERWRITE paimon.test.mytable_v7 SELECT * FROM paimon.test.mytable_v8;
![image](https://github.com/apache/incubator-paimon/assets/75019445/d8beb20d-dc36-4f44-8788-70d5b3d0cd4d)
![image](https://github.com/apache/incubator-paimon/assets/75019445/39d3e641-91f1-41e8-876e-2db0de601cba)

### What doesn't meet your expectations?

The streaming query result only contains deleted data, not inserted data, and Spark batch dynamic overwrite has the same problem

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Take a look to `streaming-read-overwrite`.
