### ISSUE TITLE
[Bug]  paimon local mode strongly depends on hadoop

### ISSUE THREAD

**Issue by Zzm0809** [apache/paimon#2667]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.6

### Compute Engine

flink

### Minimal reproduce step

<img width="874" alt="image" src="https://github.com/apache/incubator-paimon/assets/58576849/88c48080-0296-4ab7-ad23-a2e04aa5b2d6">

<img width="981" alt="image" src="https://github.com/apache/incubator-paimon/assets/58576849/b4fa6ead-9f6b-4f5d-ac45-fbdc3c0d488c">

### What doesn't meet your expectations?

When using the paimon local function, there is no need to rely on hadoop

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
orc rely on hadoop dependencies...

**Comment by JingsongLi** [comment]
if you have some idea, you can create a new issue.
