### ISSUE TITLE
[Feature]  Whole database compression combined mode does not support append unware bucket table

### ISSUE THREAD

**Issue by thomasg19930417** [apache/paimon#2670]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Whole database compression combined mode does not support append unware bucket table。
![f7467db14a7d8d34906f776d5695c4e3](https://github.com/apache/incubator-paimon/assets/20243868/dc60b912-fa0e-4e3e-8712-d55337cfea95)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by wg1026688210** [comment]
assign to me plz

**Comment by wg1026688210** [comment]
Hi~ @thomasg19930417  Can you provide the command ?

**Comment by thomasg19930417** [comment]
> Hi~ @thomasg19930417 Can you provide the command ?

Use the entire database compression command and specify the compression mode --mode combined, and the table is an append table. There are no other special parameters.
