### ISSUE TITLE
[Bug] Data error when using paimon as lookup table in Flink streaming job

### ISSUE THREAD

**Issue by bridgeDream** [apache/paimon#2833]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.8

### Compute Engine

Flink

### Minimal reproduce step

1. create a paimon table with 'merge-engine' = 'deduplicate'、'deduplicate.ignore-delete' = 'true'、'sequence.field' = 'version'
2. start a flink job which lookup paimon table with id = '100'
3. insert into paimon 
    +I[id = 100, version = 100, value = 100]
    -D[id = 100, version = 200, value = 200]
    +I [id = 100, version = 1, value = 1]
4. flink job which lookup paimon table will output record [xxx, id = 100, version = 1, value = 1]

which indicate property of 'deduplicate.ignore-delete' = 'true' doesn't work.

### What doesn't meet your expectations?

The property 'deduplicate.ignore-delete' = 'true' doesn't work in lookup paimon table in flink.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Hi @bridgeDream , now delete/ub records will be ignored before writing. So no exception in lookup now.
