### ISSUE TITLE
[Feature] Add Procedure in flink for creating empty branch

### ISSUE THREAD

**Issue by schnappi17** [apache/paimon#2847]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

subtask of https://github.com/apache/incubator-paimon/issues/1795, adding Procedure in flink to support creating an empty branch for Paimon tables

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by herefree** [comment]
What does it mean to create an empty branch? In [pip9](https://cwiki.apache.org/confluence/display/PAIMON/PIP-9%3A+Support+Branch) , creating a branch requires specifying a tag.

**Comment by schnappi17** [comment]
> What does it mean to create an empty branch? In [pip9](https://cwiki.apache.org/confluence/display/PAIMON/PIP-9%3A+Support+Branch) , creating a branch requires specifying a tag.

Hi @herefree, this is because we need to do the full-data-correction instead of incremental-data-correction which need to re-calc all the data and write to an empty table(branch).

**Comment by herefree** [comment]
> > What does it mean to create an empty branch? In [pip9](https://cwiki.apache.org/confluence/display/PAIMON/PIP-9%3A+Support+Branch) , creating a branch requires specifying a tag.
> 
> Hi @herefree, this is because we sometimes need to do the full-data-correction instead of incremental-data-correction which need to re-calc all the data and write to an empty table(branch).
Yes，I understand.thanks for your response.
