### ISSUE TITLE
[Feature] Manage main branch for paimon

### ISSUE THREAD

**Issue by FangYongs** [apache/paimon#2884]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

subtask of #1795 , manage main branch file for paimon and use it as default branch

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by sunxiaojian** [comment]
Is this mainly about merge and replace branch?

**Comment by sunxiaojian** [comment]
@FangYongs This refers to creating a file, similar to a file named MAIN-BRANCH, which can store the specified branch directory name. When writing data, the branch name stored in the MAIN-BRANCH file can be used as the default main branch. Do I understand correctly?
