### ISSUE TITLE
[Feature] Don't store redundant primary key columns

### ISSUE THREAD

**Issue by zhongyujiang** [apache/paimon#2893]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

I found that Paimon will redundantly store the primary key columns in files with a name prefixed with `_KEY_`, this increase the query overhead and storage size. Especially when there are several primary key fields, like 5 or even more.

Is it possible to directly use the original column values to be projected as the primary key during query? I think that can reduce the load of reading and writing, as well as the storage volume.

### Solution

Generate primary key values directly from original columns instead of use redundant primary key columns.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
> ### Search before asking
> * [x]  I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.
> 
> ### Motivation
> I found that Paimon will redundantly store the primary key columns in files with a name prefixed with `_KEY_`, this increase the query overhead and storage size. Especially when there are several primary key fields, like 5 or even more.
> 
> Is it possible to directly use the original column values to be projected as the primary key during query? I think that can reduce the load of reading and writing, as well as the storage volume.
> 
> ### Solution
> Generate primary key values directly from original columns instead of use redundant primary key columns.
> 
> ### Anything else?
> _No response_
> 
> ### Are you willing to submit a PR?
> * [ ]  I'm willing to submit a PR!

Yes, of course, there is a draft: https://github.com/apache/incubator-paimon/pull/1825 but he have no time to move forward.

**Comment by zhongyujiang** [comment]
Thanks for the reply, good to know that we’re already working on this!发自我的 iPhone在 2024年2月26日，17:22，Jingsong Lee ***@***.***> 写道：﻿

Search before asking

  I searched in the issues and found nothing similar.

Motivation
I found that Paimon will redundantly store the primary key columns in files with a name prefixed with _KEY_, this increase the query overhead and storage size. Especially when there are several primary key fields, like 5 or even more.
Is it possible to directly use the original column values to be projected as the primary key during query? I think that can reduce the load of reading and writing, as well as the storage volume.
Solution
Generate primary key values directly from original columns instead of use redundant primary key columns.
Anything else?
No response
Are you willing to submit a PR?

  I'm willing to submit a PR!


Yes, of course, there is a draft: #1825 but he have no time to move forward.

**Comment by JingsongLi** [comment]
https://github.com/apache/paimon/pull/4651

**Comment by JingsongLi** [comment]
https://github.com/apache/paimon/pull/4666

**Comment by JingsongLi** [comment]
We are introducing this optimization!
