### ISSUE TITLE
[Feature] Introduce deletion vectors for primary key table

### ISSUE THREAD

**Issue by Zouxxyy** [apache/paimon#2898]
### Motivation

Position deletion is a solution to implement the Merge-On-Read (MOR) structure, which has been adopted by other formats such as Iceberg and Delta. By combining with Paimon's LSM tree, we can create a new mode with deletion vectors (bitmap to identity which row id deleted) index file unique to Paimon.

Under this mode, extra overhead (lookup and write deletion vectors index file) will be introduced during writing, but during reading, data can be directly retrieved using "data + filter with deletion vector", avoiding additional merge costs between different files. Furthermore, this mode can be easily integrated into native engine solutions like Spark + Gluten in the future, thereby significantly enhancing read performance.

PIP: https://cwiki.apache.org/confluence/x/Tws4EQ

**Comment by JingsongLi** [comment]
We have two things remaining:
1. Since there is no need to merge when reading, in this mode, we can support filter pushdown of non-PK fields!
2. Documentation for deletion vectors.

**Comment by JingsongLi** [comment]
3. Supports dv with partial-update and aggregate. Looks like current implementation is not work.
4. Supports dv with first-row.

**Comment by JingsongLi** [comment]
Thanks @Zouxxyy , all finished!
