### ISSUE TITLE
[Feature] support delete record when merge engine is partial-update

### ISSUE THREAD

**Issue by AkisAya** [apache/paimon#3048]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

for now it's not allowed to delete records in a partial-update table. even though a retract with sequence group is ok, but it is not a real delete action. suppose i want to execute a batch sql like `delete from xxx_table where id = xx`, it will throw an exception. i wonder if this delete feature is able to be complemented or not. if it can be achieved, will it be on the roadmap or if it can not be achieved can anyone explains a little bit why. thank you.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by AkisAya** [comment]
it seems i can use `insert overwrite my_table select * from my_table where !(my_condition)` as a workaournd of `delete from my_table where <my_condition>`

**Comment by AkisAya** [comment]
MergeIntoAction uses changeIgnoreMergeEngine() to delete records
```
    /**
     * The {@link CoreOptions.MergeEngine}s will process -U/-D records in different ways, but we
     * want these records to be sunk directly. This method is a workaround. Actions that may produce
     * -U/-D records can call this to disable merge engine settings and force compaction.
     */
    protected void changeIgnoreMergeEngine() {
        if (CoreOptions.fromMap(table.options()).mergeEngine()
                != CoreOptions.MergeEngine.DEDUPLICATE) {
            Map<String, String> dynamicOptions = new HashMap<>();
            dynamicOptions.put(
                    CoreOptions.MERGE_ENGINE.key(), CoreOptions.MergeEngine.DEDUPLICATE.toString());
            // force compaction
            dynamicOptions.put(CoreOptions.FULL_COMPACTION_DELTA_COMMITS.key(), "1");
            Preconditions.checkArgument(
                    table instanceof FileStoreTable, "Only supports FileStoreTable.");
            table = ((FileStoreTable) table).internalCopyWithoutCheck(dynamicOptions);
        }
    }
```

seems we can do the same to provide a delete action

**Comment by JingsongLi** [comment]
Now Spark supports COW Delete for partial-update.
