### ISSUE TITLE
[Bug] OrphanFilesClean has a chance to delete normal files

### ISSUE THREAD

**Issue by wxplovecc** [apache/paimon#3074]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

master

### Compute Engine

flink

### Minimal reproduce step

1、Start a streaming write job with ckp (5 second)
2、Sleep some time between 
`        Set<String> usedFiles = getUsedFiles();
Thread.sleep(20000)
              Map<String, Path> candidates = getCandidateDeletingFiles(); `
3、Do clean orphanFiles
4、
![企业微信截图_171102857042](https://github.com/apache/incubator-paimon/assets/3350718/f1e391a8-12af-4f1e-998e-11b65138d80b)

### What doesn't meet your expectations?

Should not delete normal file

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by yuzelin** [comment]
In previous design, `getCandidateDeletingFiles` is called after `getUsedFiles`, so it may read newly committed files, and the newly committed files are not in `usedFiles`, so these files will be deleted incorrectly, am I right? 
But we use `oldEnough` to protect the new files, so I don't know why the files are deleted. Can you explain more details?

**Comment by wxplovecc** [comment]
Yes the `getCandidateDeletingFiles` method scan file use `oldEnough` get the yestoday files, In fact the newly snapshot was updated this files, but `getUsedFiles` was not include those files because of our poor hdfs perform

**Comment by yuzelin** [comment]
Anyway, put `getUsedFiles()` after `getCandidateDeletingFiles()` is correct. I think your change is right.
