### ISSUE TITLE
[Bug] Using two different hive catalogs, create the same database and table, and the final data will enter the same table

### ISSUE THREAD

**Issue by zhongtiancai** [apache/paimon#3080]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.7.0-incubating

### Compute Engine

Flink hive-connect

### Step 1
create catalog test;
use catalog test;
create database test_db;
use database test_db;
create table test_table;
insert data in test_table;

### Step 2
create catalog test1;
use catalog test1;
create database test_db;
use database test_db;
create table test_table;
insert data in test_table;

### Step 3
select * from test1.testdb.test_table;
select * from test.testdb.test_table;

### What doesn't meet your expectations?

The results are different on hive hdfs://and file://.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhongtiancai** [comment]
![微信图片_20240323003433](https://github.com/apache/paimon/assets/16176046/0c666d58-ccb6-4478-b66b-10ab7e59e689)
code snippet

**Comment by zhuangchong** [comment]
I understand that this is not a bug. You use the same Hive Metastore, you can only have a `test_db` database, a `test_table` table.

In your code example, your `if Not Exist` statement, your `Step 2` does not really go to create a database or table.

**Comment by zhongtiancai** [comment]
![微信图片_20240323003433](https://github.com/apache/paimon/assets/16176046/89b2e3b1-a862-436d-8646-bc723caad222)
![微信图片_20240325193515](https://github.com/apache/paimon/assets/16176046/ff654b9e-d72e-4592-bd10-8ce7035e0064)

@zhuangchong  I use the same hive-config-dir, but with different warehouse parameters in the code. Is this situation considered the same on hive?

**Comment by zhuangchong** [comment]
Yes, because hive has only one metadata database.
