### ISSUE TITLE
[Feature] Flink compact procedure supports 'where' filter

### ISSUE THREAD

**Issue by yuzelin** [apache/paimon#3135]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Motivation

Support feature in #3119 .

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by herefree** [comment]
Please assign to me.

**Comment by wg1026688210** [comment]
Hi~ @yuzelin I wanna work on this, plz assign this to me

**Comment by wg1026688210** [comment]
related https://github.com/apache/paimon/pull/3394
