### ISSUE TITLE
[Bug]  query values with the same primary key

### ISSUE THREAD

**Issue by zhourui999** [apache/paimon#3157]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

0.8-snapshot

### Compute Engine

spark 3.1
flink-1.17.2

### Minimal reproduce step

A large online table with frequent data writing and updates, with a data volume of approximately 600 million. CDC synchronizes to the payment table, and after running for a period of time, it is found that the data in the table has duplicate primary keys (using SparkSQL and FlinkSQL queries will result in duplicate data). After executing compact, the same primary key will be merged out

![image](https://github.com/apache/paimon/assets/40812600/22b94204-8fe0-4486-91bc-7dc42f9cee70)

### What doesn't meet your expectations?

The query result does not have duplicate primary keys

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Thanks @zhourui999
