### ISSUE TITLE
[Bug] The 'hive.table.owner' property does not work as expected

### ISSUE THREAD

**Issue by elon-X** [apache/paimon#3171]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

paimon-0.7
paimon-0.8

### Compute Engine

flink-1.16.1
hive-2.3.7

### Minimal reproduce step

**step_1:** Execute the following SQL statements through the flink-sql client:

CREATE CATALOG my_hive WITH (
  'type' = 'paimon',
  'metastore' = 'hive',
  'uri' = 'thrift://xxx:xxx', 
  'hive-conf-dir' = '/usr/local/hive-2.3.7/conf', 
  -- 'hadoop-conf-dir' = '...', this is recommended in the kerberos environment
  'warehouse' = 'hdfs://xxx'
);

USE CATALOG my_hive;

USE paimon_db;

CREATE TABLE test_table (
    data STRING
) WITH (
    'bucket' = '-1',
    'hive.table.owner' = 'Jon'
);
see the wiki: https://paimon.apache.org/docs/master/flink/sql-ddl/

**step_2:** Upon checking the table information in the hive metastore, it was discovered that the table owner is 'root', rather than 'Jon' which was passed with 'hive.table.owner' = 'Jon'. it does not work.
<img width="613" alt="image" src="https://github.com/apache/paimon/assets/34712973/f979be48-1293-4c5d-88c5-99295f76b6b8">

**step_3:** Review the Paimon source code in the class **org.apache.paimon.hive.HiveCatalog.java**.
<img width="1186" alt="image" src="https://github.com/apache/paimon/assets/34712973/8a29b41b-78a0-423a-bac4-3a1d48ee219e">

**step_4:** Investigate the source code of hive versions 2.3.7 and 3.1.2 in the class **org.apache.hadoop.hive.metastore.api.Table.java**, it was found that there is only an 'owner' attribute, without 'table.owner', and no intermediate conversion process was observed.
<img width="1417" alt="image" src="https://github.com/apache/paimon/assets/34712973/77aabd9b-0b86-46d4-912f-6be9445b9a87">

Is there something wrong with how I'm using it, or did I miss some information?

### What doesn't meet your expectations?

the table owner setting does not meet expectations.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by herefree** [comment]
Adding Parameters to a Hive Table [#](https://paimon.apache.org/docs/master/flink/sql-ddl/#adding-parameters-to-a-hive-table)
Using the table option facilitates the convenient definition of Hive table parameters. Parameters prefixed with hive. will be automatically defined in the TBLPROPERTIES of the Hive table. For instance, using the option hive.table.owner=Jon will automatically add the parameter table.owner=Jon to the table properties during the creation process.
