### ISSUE TITLE
[Bug] After the flink job written to Paimon modifies `sink.parallelism`, the job will not be able to recover from the checkpoint

### ISSUE THREAD

**Issue by huyuanfeng2018** [apache/paimon#3232]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

master

### Compute Engine

flink

### Minimal reproduce step

1. First set the parallelism degree of 1 to write Paimon

2. Stop passing the current task

3. Modify the parallelism to be greater than 1

4. Restore from the last checkpoint

### What doesn't meet your expectations?

The job should be able to resume normally from the last checkpoint or savepoint, even if I change the parallelism of the sink

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
@huyuanfeng2018 this is a good issue, but a chain committer can reduce resource cost.

maybe we can have an option to control this.

**Comment by huyuanfeng2018** [comment]
> @huyuanfeng2018 this is a good issue, but a chain committer can reduce resource cost.
> 
> maybe we can have an option to control this.

+1. Agree
