### ISSUE TITLE
[Feature] Paimon supports Flink Connector syntax

### ISSUE THREAD

**Issue by BoYiZhang** [apache/paimon#3265]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Motivation

Paimon supports create table, supports the following statements, does not require create catalog

`

CREATE TABLE flink_table (
    id   BIGINT,
    data STRING
) WITH (
    'connector'='paimon',
    'catalog-name'='hive_prod',
    'database'='hive_db',
    'table'='hive_iceberg_table',
    --  'metastore' = 'hive',
    -- 'uri' = 'thrift://<hive-metastore-host-name>:<port>', default use 'hive.metastore.uris' in HiveConf
    -- 'hive-conf-dir' = '...', this is recommended in the kerberos environment
    -- 'hadoop-conf-dir' = '...', this is recommended in the kerberos environment
    -- 'warehouse' = 'hdfs:///path/to/warehouse', default use 'hive.metastore.warehouse.dir' in HiveConf
);

`

### Solution

same as iceberg . 

https://iceberg.apache.org/docs/latest/flink-connector/#a-complete-example

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tsreaper** [comment]
We actually support creating paimon as a temporary table, but it is not recommended, because many features can only be used with catalog.
