### ISSUE TITLE
[Feature] Support copy-on-write for partial update merge function

### ISSUE THREAD

**Issue by FangYongs** [apache/paimon#3305]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Motivation

Currently, partial update in paimon only supports mor and generates a completed changelog during full compaction. We hope that partial update will support the cow mode to directly generate complete data of columns during writing, so that downstream jobs can read the complete updated results immediately

### Solution

no

### Anything else?

no

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Try `changelog-producer = lookup`?
