### ISSUE TITLE
[Feature] addColumn move support before and last

### ISSUE THREAD

**Issue by melin** [apache/paimon#3316]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Motivation

flink cdc  ColumnPosition support: BEFORE、AFTER、FIRST、LAST 

https://github.com/apache/flink-cdc/blob/fa6e7ea51258dcd90f06036196618224156df367/flink-cdc-common/src/main/java/org/apache/flink/cdc/common/event/AddColumnEvent.java#L53

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by joyCurry30** [comment]
Is there any progress on this PR? If not, I can contribute this PR

**Comment by joyCurry30** [comment]
@melin Can you cr please?
