### ISSUE TITLE
[Feature] Support multiple fields in sequence-group

### ISSUE THREAD

**Issue by FangYongs** [apache/paimon#3372]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Motivation

Currently paimon only support one field for `sequence-group` such as `fields.g_1.sequence-group`=`a,b,c,d`. When there are multiple fields in one sequence-group, users are required to combine them into one `group field` which is long data type. We can just support comparing multiple fields in one group such as `fields.g_1,g_2,g_3.sequence-group`=`a,b,c,d`

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
You can just change to new `UserDefinedSeqComparator`.
