### ISSUE TITLE
[doc] update totalRecordCount and deltaRecordCount in understand-files.md

### ISSUE THREAD

**Issue by wpj980205** [apache/paimon#3432]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Motivation

the snapshot json in `Compact Table` part should be updated, because of the commit in `org.apache.paimon.operation.FileStoreCommitImpl`. 
![image](https://github.com/apache/paimon/assets/30515643/c08ca54f-232b-44aa-ba64-aa57f70f8bc1)

### Solution

before:
```json
{
  "version" : 3,
  "id" : 4,
  "schemaId" : 0,
  "baseManifestList" : "manifest-list-9be16-82e7-4941-8b0a-7ce1c1d0fa6d-0",
  "deltaManifestList" : "manifest-list-9be16-82e7-4941-8b0a-7ce1c1d0fa6d-1",
  "changelogManifestList" : null,
  "commitUser" : "a3d951d5-aa0e-4071-a5d4-4c72a4233d48",
  "commitIdentifier" : 9223372036854775807,
  "commitKind" : "COMPACT",
  "timeMillis" : 1684163217960,
  "logOffsets" : { },
  "totalRecordCount" : 38,
  "deltaRecordCount" : 20,
  "changelogRecordCount" : 0,
  "watermark" : -9223372036854775808
}
```

after:
```json
{
  "version" : 3,
  "id" : 4,
  "schemaId" : 0,
  "baseManifestList" : "manifest-list-9be16-82e7-4941-8b0a-7ce1c1d0fa6d-0",
  "deltaManifestList" : "manifest-list-9be16-82e7-4941-8b0a-7ce1c1d0fa6d-1",
  "changelogManifestList" : null,
  "commitUser" : "a3d951d5-aa0e-4071-a5d4-4c72a4233d48",
  "commitIdentifier" : 9223372036854775807,
  "commitKind" : "COMPACT",
  "timeMillis" : 1684163217960,
  "logOffsets" : { },
  "totalRecordCount" : 2,
  "deltaRecordCount" : -16,
  "changelogRecordCount" : 0,
  "watermark" : -9223372036854775808
}
```

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by dbac** [comment]
@wpj980205   I'm willing to submit a PR!      do  modify the content in the document and replace it according to the above content?    the path is 
![image](https://github.com/user-attachments/assets/faf527a5-af39-49f0-b7b3-537d13493b15)
