### ISSUE TITLE
[Bug] Creating a tag directory is not a perfect fix

### ISSUE THREAD

**Issue by Hi-luca-Gao** [apache/paimon#3488]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

0.8.0 && 0.9-snapshot

### Compute Engine

flink1.17

### Minimal reproduce step

@JingsongLi
![image](https://github.com/apache/paimon/assets/170092135/f7a37fbc-9712-4a62-8b58-59fda49b8ab0)

I think this kind of repair will have unexpected dangers, so it should be watermark == Long.MIN.
A timestamp less than 00:00:00 on January 1, 1970 Greenwich Mean Time is a negative number.
This is a normal phenomenon。
for example：
-315585870 ===>1960-01-01T10:15:30+01:00

### What doesn't meet your expectations?

None

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by LinMingQiang** [comment]
You are right,sorry I missed this case.
