### ISSUE TITLE
[Bug] java.lang.UnsatisfiedLinkError: com.github.luben.zstd.ZstdInputStreamNoFinalizer.recommendedDInSize()J

### ISSUE THREAD

**Issue by zenoprod** [apache/paimon#3492]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

0.8

### Compute Engine

hive

### Minimal reproduce step

using hive to query table which is flink created paimon table, enconterd following question.
i searched google,don't know what's the problem. so  reported it as a bug

[hive_paimon.log](https://github.com/user-attachments/files/15747535/hive_paimon.log)

### What doesn't meet your expectations?

it should show data that stored in the table

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by ztwu** [comment]
hello, 请问下如何解决这个问题的？

**Comment by Chouving77** [comment]
hello 请你你使用的hive版本是多少

**Comment by Chouving77** [comment]
hello 请你你使用的hive版本是多少

**Comment by Chouving77** [comment]
Hello, what version of hive are you using? I have the same problem.

**Comment by userkdg** [comment]
> Hello, what version of hive are you using? I have the same problem.

我这边出现相同问题是在hive 2.1.1-cdh6.3.2中

**Comment by Chouving77** [comment]
> > Hello, what version of hive are you using? I have the same problem.
> 
> 我这边出现相同问题是在hive 2.1.1-cdh6.3.2中

是的 我也是用这个版本的 paimon-hive-connector 出现问题 ，不过我的hive版本是2.1.1-cdh6.2.1 不确定是否有兼容问题

**Comment by Chouving77** [comment]
> > Hello, what version of hive are you using? I have the same problem.
> 
> 我这边出现相同问题是在hive 2.1.1-cdh6.3.2中

我这边是hivecli访问没问题，hiveserver2访问有问题，因为hiveserver2先加载了hadoop的jar，hadoop里面有一个低版本的zstd包，现在的解决办法是把paimon-hive 用的zstd包单独放到hive/lib下

**Comment by hz-git** [comment]
> > Hello, what version of hive are you using? I have the same problem.
> 
> 我这边出现相同问题是在hive 2.1.1-cdh6.3.2中

请问各位大佬，是怎么解决paimon在hive2.1.1-CDH6.3.1/6.3.2中，zstd问题的，我先前解决办法是替换/opt/cloudera/parcels/CDH/jars下的zstd-jni-1.3.8-1.jar为zstd-jni-1.5.5-11.jar，并且要重新上传yarn的MR框架（CM页面--》yarn--》操作--》安装YARN MapReduce框架JAR，保证这个在HDFS上的JAR中包含的zstd-jni只有zstd-jni-1.5.5-11.jar），但不知道这么做有没有什么影响。
