### ISSUE TITLE
[Bug] 'tag.num-retained-max' is unavailable

### ISSUE THREAD

**Issue by xyk0930** [apache/paimon#3502]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

0.9

### Compute Engine

spark3.5.1

### Minimal reproduce step

1.A paimon table is created with 'tag.num-max' = 10. The complete configuration information is retained below
TBLPROPERTIES (
  'bucket' = '-1',
  'changelog-producer' = 'none',
  'deletion-vectors.enabled' = 'false',
  'dynamic-bucket.initial-buckets' = '20',
  'dynamic-bucket.target-row-num' = '2000000',
  'file.compression' = 'snappy',
  'file.format' = 'parquet',
  'ignore-delete' = 'false',
  'merge-engine' = 'deduplicate',
  'path' = 'hdfs://hadoop105:8020/paimon/warehouse/paimon.db/dws_follow_record',
  'primary-key' = 'id',
  'snapshot.expire.limit' = '10',
  'snapshot.num-retained.max' = '2147483647',
  'snapshot.num-retained.min' = '10',
  'snapshot.time-retained' = '1 h',
  'tag.num-retained-max' = '10')
2.I manually wrote some data and created the tag, and here is the result of SELECT * FROM 'dws_follow_record$tags'
![image](https://github.com/apache/paimon/assets/57938601/9d32c9c0-51f9-4d08-9144-be8e0401d818)

### What doesn't meet your expectations?

I set 'tag.num-max' = 10, why can I query 12 tags

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by xyk0930** [comment]
i create tag by spark procedures ，as CALL sys.create_tag(table => '" + tableName + "', tag => '" + tag + "')

**Comment by Zouxxyy** [comment]
Currently only automatically created tags (`tag.automatic-creation`) are controlled by `tag.num-max`, I think we should fix it

**Comment by Zouxxyy** [comment]
CC @yuzelin
