### ISSUE TITLE
[Bug] When metastore.partitioned-table is enabled, the partition information in hms will not be deleted after the expired partition is automatically deleted.

### ISSUE THREAD

**Issue by codeTai** [apache/paimon#3514]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

0.8-SNAPSHOT

### Compute Engine

Flink

### Minimal reproduce step

When metastore.partitioned-table is enabled, the partition information in hms will not be deleted after the expired partition is automatically deleted.

### What doesn't meet your expectations?

Expired partition information in hms is not deleted, causing partition information to accumulate

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by gsralex** [comment]
please assign to me
