### ISSUE TITLE
[Bug] Tag createTime is null

### ISSUE THREAD

**Issue by wForget** [apache/paimon#3556]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

0.8.0

### Compute Engine

spark

### Minimal reproduce step

auto create tag using process-time

![image](https://github.com/apache/paimon/assets/17894939/9b64a72f-bb3a-41cc-bf23-147d87227ad7)

### What doesn't meet your expectations?

Tag `createTime` should always be set.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Hi @wForget , this is because we need to be compatible to old readers. Very regretful, the `JsonIgnoreProperties(ignoreUnknown = true)` not be set in Snapshot for old versions.

**Comment by JingsongLi** [comment]
Hi @wForget , I closed #3557, we can discuss here.

**Comment by wForget** [comment]
> Hi @wForget , this is because we need to be compatible to old readers. Very regretful, the `JsonIgnoreProperties(ignoreUnknown = true)` not be set in Snapshot for old versions.

Thanks for the explanation, but I still don't understand why this is blocking, it is always possible to write to the new added tagTimeRetained and tagCreateTime fields.

**Comment by JingsongLi** [comment]
@wForget 
- New writer write new tag, there is a `tagCreateTime` field.
- Old reader read this tag, failed, because of json unknown field exception.

**Comment by JingsongLi** [comment]
I add this comments:

```
// When timeRetained is not defined, please do not write the tagCreatorTime field,
// as this will cause older versions (<= 0.7) of readers to be unable to read this
// tag.
// When timeRetained is defined, it is fine, because timeRetained is the new
// feature.
```

**Comment by wForget** [comment]
> @wForget
> 
> * New writer write new tag, there is a `tagCreateTime` field.
> * Old reader read this tag, failed, because of json unknown field exception.

Got it, thanks.
