### ISSUE TITLE
[Bug] mysqlcdc2paimon does not support field comment synchronization

### ISSUE THREAD

**Issue by Pandas886** [apache/paimon#3558]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

0.8

### Compute Engine

flink1.18

### Minimal reproduce step

During the running of the Flink synchronization task, the comments for the field `col1` in the MySQL source table `tb1` were modified, but the corresponding table schema in Paimon was not updated synchronously.

### What doesn't meet your expectations?

Synchronize the field annotations of the source table to the paimon table.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by LinMingQiang** [comment]
`flink mysql cdc` do not support comment schema change yet.

**Comment by zhuangchong** [comment]
related issue: #3666

**Comment by zhuangchong** [comment]
Already supported.
