### ISSUE TITLE
[Feature] Optimize heap memory usage during full compaction of manifest files

### ISSUE THREAD

**Issue by codeTai** [apache/paimon#3590]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Motivation

When submitting a snapshot triggers a full compaction of the manifest file, we hope to reduce the usage of the taskManager heap memory.

### Solution

Based on the background that writing HDFS files is slow but reading HDFS files is fast, the code logic is optimized to avoid reading multiple manifest files at the same time and accumulating data in the memory.

### Anything else?

Part of the debug log：
![image](https://github.com/apache/paimon/assets/20182632/b6e3a7ca-819d-4c98-9500-a06c516729b7)

Heap memory usage before optimization：

![image](https://github.com/apache/paimon/assets/20182632/d368dce2-0003-4285-a3cf-47bfb307dfb8)

Heap memory usage after optimization：
![image](https://github.com/apache/paimon/assets/20182632/533a7fdf-405b-4474-9c69-b633b4224b9e)

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Hi @codeTai , I created #3598 for using `ScanParallelExecutor.parallelismBatchIterable`, can you validate this PR?

**Comment by JingsongLi** [comment]
@codeTai If #3598 cannot solve your problem, please create a new pull request.

**Comment by codeTai** [comment]
Ok, I'll test it later.

**Comment by codeTai** [comment]
ScanParallelExecutor.parallelismBatchIterable  can solve my problem, thanks.
