### ISSUE TITLE
[Feature] org.apache.paimon.table.Table add listTags & listPartitions api

### ISSUE THREAD

**Issue by melin** [apache/paimon#3626]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Motivation

need to collect tag and partition information about the paimon table. It is inconvenient to query these information using spark or flink sql. Can the java api be supported to read this information?

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by LinMingQiang** [comment]
> 有API 能够获取到tags 信息，没有api 获取分区信息：
> 
> ```java
> Identifier identifier = Identifier.create("bigdata", "paimon_order_pt_tag");
> FileStoreTable table = (FileStoreTable) catalog.getTable(identifier);
> System.out.println(table.bucketMode());
> 
> TagManager tagManager = table.tagManager();
> List<Pair<Tag, String>> tags = tagManager.tagObjects();
> ```

fileStoreTable.store().newScan().readPartitionEntries
