### ISSUE TITLE
Error writing in Apache Paimon Table Append only writer can not accept row with RowKind UPDATE_BEFORE

### ISSUE THREAD

**Issue by irodriguezclaveria** [apache/paimon#3689]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

Hi all !!

I'm trying to move data from Debezium format to Paimon Table in a job flink, I've created the Apache Paimon table with the following format:

	" 'write-mode' = 'upsert'," +
" 'sequence.field' = 'updateddat' " +

### Compute Engine

Hi !

I've tried to create Paimon table in a Flink job from data to comes from Debezium. The Paimon table created has the following configuration:

```
	" 'write-mode' = 'upsert'," +
	" 'sequence.field' = 'updateddat' " +
```

and:

`"table.exec.sink.upsert-materialize", "none"`

But I have the following error:
```

Caused by: java.lang.IllegalStateException: Append only writer can not accept row with RowKind UPDATE_BEFORE
	at org.apache.paimon.utils.Preconditions.checkState(Preconditions.java:204)
	at org.apache.paimon.table.AppendOnlyFileStoreTable.lambda$newWrite$1(AppendOnlyFileStoreTable.java:151)
```

### Minimal reproduce step

- Try to copy data from Debezium format: https://nightlies.apache.org/flink/flink-docs-master/docs/connectors/table/formats/debezium/
- Y table created using apache paimon catalog.

### What doesn't meet your expectations?

n/a

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by LinMingQiang** [comment]
you need to set primary key in your table.

**Comment by irodriguezclaveria** [comment]
Hi , ok, I see now. My primary key was set, but the problem seems that the schema was created before to set the primary key, so... I had have to remove the schema file and then it has worked. 

Thanks so much.
