### ISSUE TITLE
[hotfix] fix deprecated method getRootCause() in assertj.

### ISSUE THREAD

**Issue by zhuangchong** [apache/paimon#3695]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Motivation

getRootCause() is deprecated

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by xuzifu666** [comment]
@zhuangchong Could you assgine to me，thanks~
