### ISSUE TITLE
[Bug] The expired partition's file is not reflect in the Levels

### ISSUE THREAD

**Issue by Aitozi** [apache/paimon#3817]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

master

### Compute Engine

.

### Minimal reproduce step

Currently, the levels only reflect updates to compaction before and after files. If the partition expires, the files are dropped in the committer operator without notifying the writer. This can result in a potentially inconsistent file view during lookup compaction process.

### What doesn't meet your expectations?

.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Aitozi** [comment]
This could lead to file conflicts or the FileNotFoundException

**Comment by JingsongLi** [comment]
https://github.com/apache/paimon/pull/3518 is to solve this.

**Comment by Aitozi** [comment]
thanks
