### ISSUE TITLE
[Bug] The Source Data Fetcher thread may not exit during job failover

### ISSUE THREAD

**Issue by Aitozi** [apache/paimon#4092]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

0.9

### Compute Engine

Flink

### Minimal reproduce step

![image](https://github.com/user-attachments/assets/0b774f3f-b9ff-4150-b72d-4182e94efb4b)

If the task block at poll method, it will hung forever. Besides, this lead to the FileSourceSplitReader can not be close which will bring the memory leak

![image](https://github.com/user-attachments/assets/f88ce595-ac25-4c94-aeda-9ce52a00eb4a)

### What doesn't meet your expectations?

We should wakeup from the `poll` method during the shutdown

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
Hi, can you explain the whole case? Under what circumstances would it hang?

**Comment by Aitozi** [comment]
1. The last RecordIterator is fetched and add in elementQueue and have not been completed polled out.
2. The source task failover, and want to shutdown the FetchTask, the fetchTask is block on the `pollEntry` because the RecordIterator is not released. then this thread will not exit.

We can observe this log in the taskmanager

![image](https://github.com/user-attachments/assets/0cbd681b-e5be-411a-abc8-decd7a4c9d79)
