### ISSUE TITLE
[Bug] Different Serializing Name

### ISSUE THREAD

**Issue by zmlcc** [apache/paimon#4182]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

since 0.8.0

### Compute Engine

any

### Minimal reproduce step

`deletionVectorsRanges` is given different serialization name as  [_DELETION_VECTORS_RANGES](https://github.com/apache/paimon/blob/release-0.9.0-rc1/paimon-core/src/main/java/org/apache/paimon/index/IndexFileMeta.java#L56) In  `IndexFileMeta` and  [_DELETIONS_VECTORS_RANGES](https://github.com/apache/paimon/blob/release-0.9.0-rc1/paimon-core/src/main/java/org/apache/paimon/manifest/IndexManifestEntry.java#L59) in `IndexManifestEntry`. This is maybe only an unintentional spelling mistake, but would create potential inconsistencies

### Anything else?

Can we use the same name for serialization ?  Should reserve `_DELETIONS_VECTORS_RANGES` in  `IndexManifestEntry`  to keep the index manifest file consistent

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Shadowell** [comment]
Reserve `_DELETION_VECTORS_RANGES` in `IndexFileMeta` might be better？ cc @JingsongLi

**Comment by Shadowell** [comment]
If this change not to affect future user upgrades, keeping the `_DELETIONS_VECTORS_RANGES` might be the best option.

**Comment by JingsongLi** [comment]
> If this change not to affect future user upgrades, keeping the `_DELETIONS_VECTORS_RANGES` might be the best option.

agree with you
