### ISSUE TITLE
[Feature] Implement distributed orphan file clean for spark

### ISSUE THREAD

**Issue by JingsongLi** [apache/paimon#4184]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Motivation

For large tables, there are a lot of files, and the current single-machine program may lead to OOM (Out of Memory) issues. We should introduce distributed execution to avoid OOM and performance problems.

In https://github.com/apache/paimon/pull/4181 , we have a distributed orphan file clean for Flink.

We should modify Spark too.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by xuzifu666** [comment]
Had submit a pr to support it. https://github.com/apache/paimon/pull/4196

**Comment by xuzifu666** [comment]
Refer Flink logic, support spark distributed for it. https://github.com/apache/paimon/pull/4199

**Comment by ulysses-you** [comment]
pr: https://github.com/apache/paimon/pull/4207
