### ISSUE TITLE
[Feature] In paimon catalog, add partition  query and cache

### ISSUE THREAD

**Issue by liaowanyou** [apache/paimon#4205]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Motivation

In the OLAP scenario, it is necessary to obtain the maximum partition of the table.Currently, the partition is obtained through createReader, which takes about 500ms. Therefore, it is necessary to add partition query and cache in paimon catalog

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by macdoor** [comment]
+1

**Comment by wwj6591812** [comment]
good feature
+1
