### ISSUE TITLE
[Feature] Support Flink sourceIdleTime metric in Paimon Source

### ISSUE THREAD

**Issue by xiangyuf** [apache/paimon#4249]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Motivation

We need sourceIdleTime metric to get the right currentFetchEventTimeLag metric. User also need sourceIdleTime metric to monitor how long the source table has not been updated.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by qingfei1994** [comment]
Hi @xiangyuf, may I work on this issue?

**Comment by xiangyuf** [comment]
> Hi @xiangyuf, may I work on this issue?

@qingfei1994 thx for volunteering, you can take this task. You can also work on this(https://github.com/apache/paimon/issues/4244) if you have time.

**Comment by xiangyuf** [comment]
@JingsongLi  Could you help assign this to @qingfei1994 ?
