### ISSUE TITLE
[Feature] Branch allows for setting expiration times.

### ISSUE THREAD

**Issue by sunxiaojian** [apache/paimon#4274]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Motivation

Branch supports expiration time

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by LinMingQiang** [comment]
Why we need this feature?

**Comment by sunxiaojian** [comment]
> Why we need this feature?

By setting an expiration time, you can automatically manage the lifecycle of branches. For example, you can automatically delete them when experimental branches are no longer needed.   Same meaning as "tag.defilt-time-retained" in tag

**Comment by JingsongLi** [comment]
I doubt this, branch is a heavy concept to me, it should no be quietly expired.

**Comment by sunxiaojian** [comment]
> I doubt this, branch is a heavy concept to me, it should no be quietly expired.

Branches that have not been maintained for a long time can be cleared, especially test branches that allow for setting retention time

**Comment by sunxiaojian** [comment]
> I doubt this, branch is a heavy concept to me, it should no be quietly expired.

For important branches, you can set no retention time, allowing for long-term existence;
For some unimportant branches, such as test branches or fix branches, a retention time can be set for easy cleaning;
Actually, I think that most branches do not need to exist for a long time and need to be cleaned up after verification

**Comment by LinMingQiang** [comment]
Because branches are not created frequently or regularly. So I think this kind of branch can be deleted manually.
