### ISSUE TITLE
[Feature] Support create table use warehouse as base location instead of hive database location when using HMS

### ISSUE THREAD

**Issue by Tan-JiaLiang** [apache/paimon#4435]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Motivation

When paimon using HMS as the metastore, the base location for create table is hive database location, I think tables in a database can store into difference object storage bucket instead of one.

### Solution

We can add a Hive Catalog option for this, the default value is false.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by Zouxxyy** [comment]
#3843

**Comment by Tan-JiaLiang** [comment]
Very thanks to @Zouxxyy
