### ISSUE TITLE
[Bug] 官网下载0.9.0的源代码版本之后，按照readme编译之后，怎么单独启动paimon

### ISSUE THREAD

**Issue by Qinghan25** [apache/paimon#4460]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

0.9.0

### Compute Engine

没有使用，单独启动paimon

### Minimal reproduce step

- Run the `mvn clean install -DskipTests` command to build the project.
- Run the `mvn spotless:apply` to format the project (both Java and Scala).
- IDE: Mark `paimon-common/target/generated-sources/antlr4` as Sources Root.

执行了前面两个命令

### What doesn't meet your expectations?

希望了解不集成别的组件 paimon是否可以单独启动

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by wg1026688210** [comment]
可以在IDEA里面找些E2E的单元测试

**Comment by JackeyLee007** [comment]
Paimon只是一个存储引擎。它没有自己的服务，甚至没有自己的计算引擎，而是借助Flink或Spark执行。

**Comment by JingsongLi** [comment]
@Qinghan25 Please use English, this is in the Apache community.
