### ISSUE TITLE
[Bug] 在starrocks中建立paimon_catalog，怎么访问paimon里面的表

### ISSUE THREAD

**Issue by Qinghan25** [apache/paimon#4474]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

0.9.0

### Compute Engine

flink-1.20.0

### Minimal reproduce step

按照官网步骤https://paimon.apache.org/docs/0.9/flink/quick-start/，建my_catalog和表word_count,怎么在starrocks里面建立paimon_catalog.
my_catalog语句：服务器为243
CREATE CATALOG my_catalog WITH (
    'type'='paimon',
    'warehouse'='file:/home/rim/paimon'
);
starrocks 为别的ip的服务器

### What doesn't meet your expectations?

希望知道怎么建立paimon_catalog 

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by liming30** [comment]
@Qinghan25 You can refer to  https://paimon.apache.org/docs/master/engines/starrocks/#create-paimon-catalog to create paimon's external catalog in starrocks. For more detailed steps, please refer to the starrocks doc https://docs.starrocks.io/docs/data_source/catalog/paimon_catalog/.

From your description, it seems that you want to use another starrocks machine to access the local filesystem data. I think you should use a distributed file system, such as HDFS, S3, etc. to ensure that it can be accessed in a distributed environment.

**Comment by JingsongLi** [comment]
@Qinghan25  Please use English, this is in the Apache community.
