### ISSUE TITLE
[Bug] Fail to create tag automatically with watermark

### ISSUE THREAD

**Issue by JackeyLee007** [apache/paimon#4481]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

0.9

### Compute Engine

Flink-1.18.1
Standalone cluster.

### Minimal reproduce step

```sql
-- Target paimon table with tags create automatically from watermark 
create table orders_with_watermark(
    id INT PRIMARY KEY NOT ENFORCED, 
    val int, 
    create_time TIMESTAMP(3), 
    update_time TIMESTAMP(3),
    WATERMARK FOR `update_time` AS `update_time` - INTERVAL '5' SECOND  
  ) 
  WITH (
    'tag.automatic-creation' = 'watermark',
    'tag.creation-period' = 'hourly',
    'tag.creation-delay' = '10 m',
    'tag.num-retained-max' = '90',
    'sink.watermark-time-zone' = 'Asia/Shanghai'
);
-- mock datasource 
CREATE TEMPORARY TABLE datagen_table (
    id INT,
    name STRING,
    ts TIMESTAMP(3)
) WITH (
    'connector' = 'datagen',
    'rows-per-second' = '1',
    'fields.id.min' = '1',
    'fields.id.max' = '100',
    'fields.name.length' = '10',
    'fields.ts.kind' = 'random'
);
-- Run a stream job on Flink
INSERT INTO  orders_with_watermark
  select id, 1, now(), now() 
  from datagen_table;
```

### What doesn't meet your expectations?

The tags should be created automatically every hour, but none.
No tag files could be found under the table folder and also no result when executing the following sql
```sql
select * from `orders_with_watermark$tags` 
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
First, you can check if the job is heath.
Second, you can check the watermark in Flink topology, does the source produces the watermark normally.

**Comment by JackeyLee007** [comment]
Sorry, it's my fault. Actually, the watermark should be emitted from the stream source which is the datagen_table for this case.

**Comment by JackeyLee007** [comment]
Thanks for your hint. @JingsongLi
