### ISSUE TITLE
Should DeletionVectorsMaintainer keep thread-safe?

### ISSUE THREAD

**Issue by stayrascal** [apache/paimon#4579]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

master: 16a405882cd8f0ca9afbe8566b919aef930144ef

### Compute Engine

flink

### Minimal reproduce step

1. it's hard to reproduce since it's not a deterministic problem, the stack as follow:
```
Caused By: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1469)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1503)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1501)
	at org.apache.paimon.deletionvectors.DeletionVectorIndexFileWriter.tryWriter(DeletionVectorIndexFileWriter.java:78)
	at org.apache.paimon.deletionvectors.DeletionVectorIndexFileWriter.write(DeletionVectorIndexFileWriter.java:68)
	at org.apache.paimon.deletionvectors.DeletionVectorsIndexFile.write(DeletionVectorsIndexFile.java:154)
	at org.apache.paimon.index.IndexFileHandler.writeDeletionVectorsIndex(IndexFileHandler.java:293)
	at org.apache.paimon.deletionvectors.DeletionVectorsMaintainer.writeDeletionVectorsIndex(DeletionVectorsMaintainer.java:117)
    at org.apache.paimon.compact.CompactDeletionFile.generateFiles(CompactDeletionFile.java:45)
    at org.apache.paimon.compact.CompactDeletionFileSLazyCompactDeletionFile.getOrCompute(CompactDeletionFile.java:121)
    at org. apache.paimon.operation.AbstractFileStoreWrite.prepareCommit(AbstractFileStoreWrite.java:217)
    at org.apache.paimon.operation.MemoryFileStoreWrite.prepareCommit(MemoryFileStorewrite.java:154)
```

2. I'm trying to add a new parallel test case in DeletionVectorsMaintainerTest
```
@Test
    void testParallelNotifyNewDeletionAndWriteIndex() {
        DeletionVectorsMaintainer.Factory factory =
                new DeletionVectorsMaintainer.Factory(fileHandler);
        DeletionVectorsMaintainer dvMaintainer =
                factory.createOrRestore(null, BinaryRow.EMPTY_ROW, 0);

        ThreadPoolExecutor threadPool = ThreadPoolUtils.createCachedThreadPool(2, "dv-");
        Runnable delete = () -> {
            for (int i = 0; i < 1000; i++) {
                dvMaintainer.notifyNewDeletion("f" + i, i);
                try {
                    Thread.sleep(10);
                } catch (InterruptedException e) {
                    throw new RuntimeException(e);
                }
            }
        };

        Runnable compact = () -> {
            for (int i = 0; i < 100; i++) {
                dvMaintainer.writeDeletionVectorsIndex();
                try {
                    Thread.sleep(50);
                } catch (InterruptedException e) {
                    throw new RuntimeException(e);
                }
            }
        };

        Future<?> deleteFuture = threadPool.submit(delete);
        Future<?> compactFuture = threadPool.submit(compact);

        try {
            compactFuture.get();
            deleteFuture.get();
        } catch (ExecutionException | InterruptedException e) {
            throw new RuntimeException(e);
        }

        dvMaintainer.notifyNewDeletion("f1001", 1001);
        List<IndexFileMeta> indexFileMetas = dvMaintainer.writeDeletionVectorsIndex();
        Assert.assertEquals(1, indexFileMetas.size());
        Assert.assertEquals(1001, indexFileMetas.get(0).rowCount());
    }
```

### What doesn't meet your expectations?

1. Not sure if I misunderstand the whole sink process, it seems that the data writing(traverse WriteBuffer and writing) and async compact task running concurrently, so the it might caused that data writing thread modify the deletionVectors of DeletionVectorsMaintainer while the compact thread is traversing the deletionVectors and write to index, and then it leads to CME problem.

2. if the  problem above all mentioned really exists, will we keep the DeletionVectorsMaintainer as a thread-safe maintainer, or change the type of deletionVectors, e.g. queue? 

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
In `TableWriteImpl.prepareCommit`, the `waitCompaction` should be true, in this way, only one thread will access the deletion vectors maintainer.

**Comment by stayrascal** [comment]
> In `TableWriteImpl.prepareCommit`, the `waitCompaction` should be true, in this way, only one thread will access the deletion vectors maintainer.
> 
> I think this is a bug in flink-cdc.

Got it, thanks for explanation. 

One more question, when the `waitCompaction` will be false? it seems only test cases will pass false. Or if it's better that the `TableWriteImpl.prepareCommit` check value of waitCompaction in case the caller pass wrong value?

**Comment by JingsongLi** [comment]
@stayrascal If the waitCompaction is false, CompactDeletionFile should be another implementation. I think we can have a check here.

**Comment by stayrascal** [comment]
> @stayrascal If the waitCompaction is false, CompactDeletionFile should be another implementation. I think we can have a check here.

Got it, thanks.

**Comment by leonardBang** [comment]
> In `TableWriteImpl.prepareCommit`, the `waitCompaction` should be true, in this way, only one thread will access the deletion vectors maintainer.
> 
> I think this is a bug in flink-cdc.

Let's fix this issue in flink-cdc, tracked in FLINK-36790
