### ISSUE TITLE
[Bug] The dynamic bucket in the primary key table does not take effect.

### ISSUE THREAD

**Issue by chenjiehao** [apache/paimon#4633]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon/issues) and found nothing similar.

### Paimon version

1.0-SNAPSHOT

### Compute Engine

flink-1.20

### Minimal reproduce step

CREATE TABLE word_count_1 (
    word STRING PRIMARY KEY NOT ENFORCED,
    cnt BIGINT
)WITH (
 'bucket' = '-1',
 'dynamic-bucket.target-row-num' ='100000',
 'write-only'= 'true'
);

CREATE TEMPORARY TABLE word_table (
    word STRING
) WITH (
    'connector' = 'datagen',
    'fields.word.length' = '1'
);

insert into word_count_1 select word,2 from word_table;
![WX20241204-145027](https://github.com/user-attachments/assets/9ff467c8-9fd7-4fee-9700-0fb4c1ad1da5)

![WX20241204-145115@2x](https://github.com/user-attachments/assets/d6364dd6-c0fc-47e1-8704-589eacaf8402)

### What doesn't meet your expectations?

The number of buckets in the primary key table is automatically expanded based on the configuration parameters.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by qyfftf** [comment]
Your `datagen` table configuration has `fields.word.length=1`, which means it can only generate 16 unique values: `1-9` and `a-f`. Therefore, when writing to a Paimon primary key table with `word` as the primary key, there will actually be only 16 rows.
![image](https://github.com/user-attachments/assets/6e77aa30-7457-4968-b011-c67aa6271af4)
