### ISSUE TITLE
[Bug] Paimon does not support multiple writers into the same table and topic

### ISSUE THREAD

**Issue by JingsongLi** [apache/paimon#745]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Paimon version

0.4

### Compute Engine

flink

### Minimal reproduce step

When creating two different streaming jobs that INSERT INTO the same table and kafka topic, the second job is never able to make progress as the transaction gets constantly aborted due to the producer getting fenced.

### What doesn't meet your expectations?

Paimon should set the transactionalIdPrefix to avoid transactions of different jobs clashing.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by schnappi17** [comment]
I'm willing to take this issue @JingsongLi , thanks!
