### ISSUE TITLE
[Feature] Allow tuning of transaction timeout

### ISSUE THREAD

**Issue by JingsongLi** [apache/paimon#754]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon/issues) and found nothing similar.

### Motivation

Paimon sets the producer transaction timeout to 1hr. The maximum allowed by a kafka broker is 15 mins. This causes exceptions to be thrown and the job dies when kafka log is enabled on a table. 

### Solution

From Alex Sorokoumov:

Yeah! I think it would be generally useful to be able to override Paimon defaults on the Catalog level. In fact, the Paimon Catalog already overrides Table's connector and path fields using its type and warehouse fields. We would extend that to provide arbitrary fields. For example, the table below gets log.system and kafka options from the Catalog:

CREATE CATALOG table_store_catalog WITH (
    'type'='table-store',
    'warehouse'='s3://my-bucket/table-store',
    'log.system' = 'kafka',
    'kafka.bootstrap.servers' = '<list of kafka brokers>',
    'kafka.transaction.timeout.ms' = '900000',
 );

USE CATALOG table_store_catalog;

CREATE TABLE word_count (
    word STRING PRIMARY KEY NOT ENFORCED,
    cnt BIGINT
) WITH (
    'kafka.topic' = 'word_count_log'
);

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by JingsongLi** [comment]
https://issues.apache.org/jira/browse/FLINK-30419

**Comment by legendtkl** [comment]
I would like to work on this. 

Would you assign it to me ?@JingsongLi
